"""
core/extractor.py — Structured data extraction & database hydration utility.

Takes raw Markdown text generated by the OCR step, extracts specific 
data points into a strict Pydantic schema using a text-based LLM, and
persists normalized metadata and 1024-d chunk embeddings into PostgreSQL.
"""

import json
import logging
import re
import uuid
from datetime import datetime, date
from typing import Optional
import pydantic
from sqlalchemy.orm import Session

try:
    from dateutil.relativedelta import relativedelta
except ImportError:
    relativedelta = None

from core.prompts import CERTIFICATE_EXTRACTION_SYSTEM_PROMPT, EXTRACTION_SYSTEM_PROMPT
from schemas.extraction import CertificateExtractionSchema, CertificateMetadata, CertificateChunk
from storage.models import AuthorityLookup, SupplierLookup
from core.rag.chunker import chunk_for_qa
from core.rag.embeddings import get_embeddings_batch

logger = logging.getLogger(__name__)


def _normalize_text(text: str) -> str:
    if not text:
        return ""
    return re.sub(r"[^A-Z0-9]", "", text.upper())


def enrich_certificate_metadata(
    data: CertificateExtractionSchema, db: Session
) -> CertificateExtractionSchema:
    """Deterministically normalizes and enriches LLM extraction using SQL lookup tables."""
    if not db:
        return data

    # 1. Authority, Country & Standard Expiration Date Resolution
    raw_auth_norm = _normalize_text(data.authority)
    if raw_auth_norm:
        authorities = db.query(AuthorityLookup).all()
        matched_auth = None

        for auth in authorities:
            canon_norm = _normalize_text(auth.canonical_authority)
            alias_norms = [_normalize_text(a) for a in (auth.aliases or [])]

            if raw_auth_norm == canon_norm or raw_auth_norm in alias_norms:
                matched_auth = auth
                break
            elif any(
                a in raw_auth_norm for a in alias_norms if len(a) >= 3
            ) or (len(raw_auth_norm) >= 3 and raw_auth_norm in canon_norm):
                matched_auth = auth
                break

        if matched_auth:
            # Deterministically assign Country if missing or null
            if not data.country or data.country.strip().lower() in [
                "none",
                "null",
                "",
                "not found",
            ]:
                data.country = matched_auth.country

            # If exp_date is missing and authority has standard validity years, calculate it
            if not data.exp_date and matched_auth.standard_validity_years:
                if data.issue_date:
                    try:
                        dt = datetime.strptime(data.issue_date, "%Y-%m-%d")
                        if relativedelta is not None:
                            dt_exp = dt + relativedelta(
                                years=matched_auth.standard_validity_years
                            )
                        else:
                            dt_exp = dt.replace(
                                year=dt.year + matched_auth.standard_validity_years
                            )
                        data.exp_date = dt_exp.strftime("%Y-%m-%d")
                    except Exception:
                        pass

    # 2. Supplier / Foreign OEM Canonicalization
    raw_supp_norm = _normalize_text(data.supplier)
    if raw_supp_norm:
        suppliers = db.query(SupplierLookup).all()
        for supp in suppliers:
            canon_norm = _normalize_text(supp.canonical_supplier)
            alias_norms = [_normalize_text(a) for a in (supp.aliases or [])]

            if (
                raw_supp_norm == canon_norm
                or raw_supp_norm in alias_norms
                or any(a in raw_supp_norm for a in alias_norms if len(a) >= 3)
            ):
                data.supplier = supp.canonical_supplier
                break

    return data


FRENCH_MONTH_MAP = {
    "janv": "jan", "janvier": "jan",
    "févr": "feb", "fevr": "feb", "fév": "feb", "fev": "feb", "février": "feb", "fevrier": "feb",
    "mars": "mar",
    "avr": "apr", "avril": "apr",
    "mai": "may",
    "juin": "jun",
    "juil": "jul", "jui": "jul", "juillet": "jul",
    "août": "aug", "aout": "aug",
    "sept": "sep", "septembre": "sep",
    "oct": "oct", "octobre": "oct",
    "nov": "nov", "novembre": "nov",
    "déc": "dec", "dec": "dec", "décembre": "dec", "decembre": "dec",
}


def _parse_iso_date(date_str: Optional[str]) -> Optional[date]:
    """
    Safely converts arbitrary date strings (YYYY-MM-DD, timestamp strings, French month
    abbreviations, DD-MMM-YY, etc.) into Python date objects.

    Notes:
    - 9999-01-01 (Excel "no expiry" sentinel) is stored as-is — do NOT treat it as None.
    - 2-digit years in regex fallback are mapped to 20xx (certificates are modern documents).
    """
    if not date_str or str(date_str).strip() in ("Not Found", "null", "None", ""):
        return None

    s = str(date_str).strip()

    # Handle "YYYY-MM-DD HH:MM:SS" or "YYYY-MM-DD 00:00:00"
    if " " in s:
        first_part = s.split()[0]
        if re.match(r"^\d{4}-\d{2}-\d{2}$", first_part):
            try:
                return datetime.strptime(first_part, "%Y-%m-%d").date()
            except ValueError:
                pass

    # Try standard YYYY-MM-DD (covers 9999-01-01 correctly)
    if re.match(r"^\d{4}-\d{2}-\d{2}$", s):
        try:
            return datetime.strptime(s, "%Y-%m-%d").date()
        except ValueError:
            pass

    # Substitute French month abbreviations
    s_lower = s.lower()
    for fr, en in FRENCH_MONTH_MAP.items():
        if fr in s_lower:
            s_lower = re.sub(r'(?<=[\d\s\-_])' + re.escape(fr) + r'(?=[\d\s\-_]|$)', en, s_lower)
            break

    try:
        import dateutil.parser
        dt = dateutil.parser.parse(s_lower, dayfirst=True)
        return dt.date()
    except Exception:
        # Fallback regex for DD-MM-YY or DD-MM-YYYY
        m = re.search(r"(\d{1,2})[-/\s](\d{1,2})[-/\s](\d{2,4})", s)
        if m:
            d_val, m_num, y = int(m.group(1)), int(m.group(2)), int(m.group(3))
            if y < 100:
                # Only in this path can we confirm the year was 2-digit in the source.
                # Always map to 20xx for certificate documents (99  2099, 24  2024).
                y += 2000
            try:
                return date(y, m_num, d_val)
            except Exception:
                pass

    logger.warning(f"Unable to parse date string '{date_str}'.")
    return None



def extract_certificate_data(
    raw_markdown: str, file_name: str, db_session: Optional[Session] = None
) -> CertificateExtractionSchema:
    """
    Extract structured data from raw Markdown text using an LLM and optionally enrich via DB.
    
    Args:
        raw_markdown: The markdown text output from the active OCR engine.
        file_name: The original filename, preserved for traceability.
        db_session: Optional active SQLAlchemy Session for lookup table enrichment.
        
    Returns:
        A validated and enriched CertificateExtractionSchema object.
    """
    # 1. Construct the LLM payload (engine formats system/user into its own template).
    from server.config import MAX_EXTRACTION_PROMPT_CHARS
    full_text = raw_markdown
    if len(raw_markdown) > MAX_EXTRACTION_PROMPT_CHARS:
        logger.warning(
            f"  Truncating extraction document from {len(raw_markdown)} to "
            f"{MAX_EXTRACTION_PROMPT_CHARS} chars to fit the LLM context window."
        )
        raw_markdown = raw_markdown[:MAX_EXTRACTION_PROMPT_CHARS]

    user_prompt = f"--- BEGIN DOCUMENT: {file_name} ---\n"
    user_prompt += f"{raw_markdown}\n"
    user_prompt += "--- END DOCUMENT ---\n\n"
    user_prompt += "Return ONLY the raw JSON output."

    # 2. Call the LLM engine to get the pure JSON string response (Full Reasoning Mode)
    from core.llm import generate_json
    from core.utils.vram import flush_gpu_cache, ensure_headroom
    from server.config import MIN_FREE_VRAM_MB
    flush_gpu_cache()
    ensure_headroom(MIN_FREE_VRAM_MB, "LLM extraction")
    raw_json_response = generate_json(
        system_prompt=CERTIFICATE_EXTRACTION_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        disable_thinking=False,
    )

    # 3. Parse and Validate with fallback
    try:
        parsed_data = CertificateExtractionSchema.model_validate_json(raw_json_response)
    except (json.JSONDecodeError, pydantic.ValidationError) as e:
        logger.warning(f"  JSON/Pydantic validation failed for {file_name}: {e}")
        logger.info("    Falling back to default 'Not Found' values to prevent crash.")
        
        parsed_data = CertificateExtractionSchema(
            component="Not Found",
            supplier="Not Found",
            country=None,
            certif_number="Not Found",
            authority="Not Found",
            issue_date=None,
            exp_date=None,
        )

    # 4. Enrich metadata with database lookups if db_session is provided
    if db_session is not None:
        parsed_data = enrich_certificate_metadata(parsed_data, db_session)

    return parsed_data


def save_certificate_to_db(
    cert_data: CertificateExtractionSchema,
    raw_markdown: str,
    file_name: str,
    db: Optional[Session] = None
) -> CertificateMetadata:
    """
    Persists structured certificate metadata and vector-embedded chunks into PostgreSQL.

    Operation Steps:
      1. Performs lookup table enrichment on Pydantic certificate schema.
      2. Converts Pydantic fields to normalized CertificateMetadata ORM record.
      3. Chunks layout-aware markdown text via chunk_for_qa().
      4. Computes 1024-dimensional BAAI/bge-m3 embeddings for every chunk.
      5. Binds chunks to metadata record via certificate_id FK.
      6. Wraps insertion in a single atomic transaction block (db.commit()) with db.rollback().

    Returns:
        CertificateMetadata: Persisted ORM metadata object.
    """
    close_session_on_exit = False
    if db is None:
        from storage.database import SessionLocal
        db = SessionLocal()
        close_session_on_exit = True

    try:
        # Perform lookup table enrichment before converting to ORM record
        cert_data = enrich_certificate_metadata(cert_data, db)

        cert_id = f"cert_{uuid.uuid4().hex[:12]}"

        # Normalize fields from Pydantic schema
        component = cert_data.component if cert_data.component != "Not Found" else None
        supplier = cert_data.supplier if cert_data.supplier != "Not Found" else None
        country = cert_data.country if cert_data.country != "Not Found" else None
        certif_number = cert_data.certif_number if getattr(cert_data, "certif_number", "Not Found") != "Not Found" else None
        authority = cert_data.authority if cert_data.authority != "Not Found" else None
        issue_dt = _parse_iso_date(cert_data.issue_date)
        exp_dt = _parse_iso_date(cert_data.exp_date)
        cert_link = getattr(cert_data, "cert_link", None) or None

        # 1. Create CertificateMetadata ORM instance
        metadata_record = CertificateMetadata(
            certificate_id=cert_id,
            component=component,
            supplier=supplier,
            country=country,
            certif_number=certif_number,
            authority=authority,
            issue_date=issue_dt,
            exp_date=exp_dt,
            cert_link=cert_link,
            file_name=file_name
        )

        # 2. Chunk markdown text
        raw_chunks = chunk_for_qa(raw_markdown, file_name, document_id=cert_id)
        chunk_texts = [c.get("content", "") for c in raw_chunks]

        # 3. Compute 1024-d dense vector embeddings via BAAI/bge-m3
        logger.info(f"Computing 1024-d embeddings for {len(chunk_texts)} chunks...")
        embeddings = get_embeddings_batch(chunk_texts)

        # 4. Construct CertificateChunk ORM instances
        chunk_records = []
        for idx, chunk_info in enumerate(raw_chunks):
            pg_num = chunk_info.get("page_number")
            if isinstance(pg_num, str) and pg_num.isdigit():
                pg_num = int(pg_num)
            elif not isinstance(pg_num, int):
                pg_num = 1

            chunk_orm = CertificateChunk(
                certificate_id=cert_id,
                page_number=pg_num,
                raw_text=chunk_info.get("content", ""),
                embedding=embeddings[idx] if idx < len(embeddings) else [0.0] * 1024
            )
            chunk_records.append(chunk_orm)

        db.add(metadata_record)
        db.add_all(chunk_records)
        db.commit()
        db.refresh(metadata_record)
        logger.info(f" Successfully persisted Certificate '{cert_id}' with {len(chunk_records)} chunks to PostgreSQL.")
        
        # Trigger automated backup
        from storage.backup import export_database_to_sql
        export_database_to_sql()
        
        return metadata_record
    except Exception as e:
        db.rollback()
        logger.error(f" Database error persisting Certificate '{cert_id}': {e}")
        raise
    finally:
        if close_session_on_exit:
            db.close()
