"""
core/extractor.py — Structured data extraction & database hydration utility.

Takes raw Markdown text generated by the OCR step, extracts specific 
data points into a strict Pydantic schema using a text-based LLM, and
persists normalized metadata and 1024-d chunk embeddings into PostgreSQL.
"""

import json
import logging
import re
import uuid
from datetime import datetime, date
from typing import Optional
import pydantic
from sqlalchemy.orm import Session

try:
    from dateutil.relativedelta import relativedelta
except ImportError:
    relativedelta = None

from core.prompts import CERTIFICATE_EXTRACTION_SYSTEM_PROMPT, EXTRACTION_SYSTEM_PROMPT
from schemas.extraction import CertificateExtractionSchema, CertificateMetadata, CertificateChunk
from storage.models import AuthorityLookup, SupplierLookup
from core.rag.chunker import chunk_for_qa
from core.rag.embeddings import get_embeddings_batch

logger = logging.getLogger(__name__)

# Sentinel date for non-expiring ("infinite"/"Perpetual") certificates. Matches the
# Excel "no expiry" convention already preserved by _parse_iso_date, so the value is
# both storable in the relational Date column and distinguishable from NULL (which is
# reserved for variable/context-dependent terms where no exp date was extracted).
NO_EXPIRY_DATE = date(9999, 1, 1)
NO_EXPIRY_DISPLAY = "infinite"

NO_EXPIRY_MARKERS = ("perpetual", "infinite", "no expiry", "no expiration")


def is_no_expiry_marker(value) -> bool:
    """True when a raw exp_date value explicitly denotes a non-expiring certificate."""
    if not value:
        return False
    return str(value).strip().lower() in NO_EXPIRY_MARKERS


def format_exp_date(value) -> Optional[str]:
    """Render an exp_date for user-facing display.

    Maps the no-expiry sentinel (9999-01-01) to "infinite"; real dates are rendered
    as YYYY-MM-DD; NULL/empty stays None.
    """
    if not value:
        return None
    if isinstance(value, datetime):
        if value.date() == NO_EXPIRY_DATE:
            return NO_EXPIRY_DISPLAY
        return value.strftime("%Y-%m-%d")
    if isinstance(value, date):
        if value == NO_EXPIRY_DATE:
            return NO_EXPIRY_DISPLAY
        return value.strftime("%Y-%m-%d")
    return str(value)


def _normalize_text(text: str) -> str:
    if not text:
        return ""
    return re.sub(r"[^A-Z0-9]", "", text.upper())


def find_matching_authority(db: Session, authority_text: Optional[str]):
    """Resolves a raw authority string to a matched AuthorityLookup row (or None)."""
    from storage.models import AuthorityLookup
    raw_auth_norm = _normalize_text(authority_text)
    if not raw_auth_norm:
        return None
    authorities = db.query(AuthorityLookup).all()
    for auth in authorities:
        canon_norm = _normalize_text(auth.canonical_authority)
        alias_norms = [_normalize_text(a) for a in (auth.aliases or [])]
        if raw_auth_norm == canon_norm or raw_auth_norm in alias_norms:
            return auth
        elif any(
            a in raw_auth_norm for a in alias_norms if len(a) >= 3
        ) or (len(raw_auth_norm) >= 3 and raw_auth_norm in canon_norm):
            return auth
    return None


def enrich_certificate_metadata(
    data: CertificateExtractionSchema, db: Session
) -> CertificateExtractionSchema:
    """Deterministically normalizes and enriches LLM extraction using SQL lookup tables."""
    if not db:
        return data

    # 1. Authority, Country & Standard Expiration Date Resolution
    matched_auth = find_matching_authority(db, data.authority)
    if matched_auth:
        # Deterministically assign Country if missing or null
        if not data.country or data.country.strip().lower() in [
            "none",
            "null",
            "",
            "not found",
        ]:
            data.country = matched_auth.country

        # Expiration date resolution driven by the authority's validity tier.
        #   - "infinite"  -> non-expiring certificate ("Perpetual")
        #   - numeric     -> issue_date + validity_years
        #   - null        -> leave the raw extracted exp_date untouched
        if not data.exp_date and matched_auth.standard_validity_years:
            validity_str = str(matched_auth.standard_validity_years).strip().lower()
            if validity_str == "infinite":
                data.exp_date = "Perpetual"
            else:
                try:
                    validity_years = int(float(validity_str))
                except (ValueError, TypeError):
                    validity_years = None
                if validity_years is not None and data.issue_date:
                    issue_dt = _parse_iso_date(data.issue_date)
                    if issue_dt is not None:
                        try:
                            if relativedelta is not None:
                                dt_exp = issue_dt + relativedelta(
                                    years=validity_years
                                )
                            else:
                                dt_exp = issue_dt.replace(
                                    year=issue_dt.year + validity_years
                                )
                            data.exp_date = dt_exp.strftime("%Y-%m-%d")
                        except Exception:
                            pass

    # 2. Supplier / Foreign OEM Canonicalization
    raw_supp_norm = _normalize_text(data.supplier)
    if raw_supp_norm:
        suppliers = db.query(SupplierLookup).all()
        for supp in suppliers:
            canon_norm = _normalize_text(supp.canonical_supplier)
            alias_norms = [_normalize_text(a) for a in (supp.aliases or [])]

            if (
                raw_supp_norm == canon_norm
                or raw_supp_norm in alias_norms
                or any(a in raw_supp_norm for a in alias_norms if len(a) >= 3)
            ):
                data.supplier = supp.canonical_supplier
                break

    return data


FRENCH_MONTH_MAP = {
    "janv": "jan", "janvier": "jan",
    "févr": "feb", "fevr": "feb", "fév": "feb", "fev": "feb", "février": "feb", "fevrier": "feb",
    "mars": "mar",
    "avr": "apr", "avril": "apr",
    "mai": "may",
    "juin": "jun",
    "juil": "jul", "jui": "jul", "juillet": "jul",
    "août": "aug", "aout": "aug",
    "sept": "sep", "septembre": "sep",
    "oct": "oct", "octobre": "oct",
    "nov": "nov", "novembre": "nov",
    "déc": "dec", "dec": "dec", "décembre": "dec", "decembre": "dec",
}


def _parse_iso_date(date_str: Optional[str]) -> Optional[date]:
    """
    Safely converts arbitrary date strings (YYYY-MM-DD, timestamp strings, French month
    abbreviations, DD-MMM-YY, etc.) into Python date objects.

    Notes:
    - 9999-01-01 (Excel "no expiry" sentinel) is stored as-is — do NOT treat it as None.
    - "Perpetual" / "infinite" / "no expiry" markers normalize to the 9999-01-01 no-expiry
      sentinel (NO_EXPIRY_DATE), keeping non-expiring certificates distinct from NULL.
    - 2-digit years in regex fallback are mapped to 20xx (certificates are modern documents).
    """
    if not date_str or str(date_str).strip() in ("Not Found", "null", "None", ""):
        return None

    s = str(date_str).strip()

    if is_no_expiry_marker(s):
        return NO_EXPIRY_DATE

    # Handle "YYYY-MM-DD HH:MM:SS" or "YYYY-MM-DD 00:00:00"
    if " " in s:
        first_part = s.split()[0]
        if re.match(r"^\d{4}-\d{2}-\d{2}$", first_part):
            try:
                return datetime.strptime(first_part, "%Y-%m-%d").date()
            except ValueError:
                pass

    # Try standard YYYY-MM-DD (covers 9999-01-01 correctly)
    if re.match(r"^\d{4}-\d{2}-\d{2}$", s):
        try:
            return datetime.strptime(s, "%Y-%m-%d").date()
        except ValueError:
            pass

    # Substitute French month abbreviations
    s_lower = s.lower()
    for fr, en in FRENCH_MONTH_MAP.items():
        if fr in s_lower:
            s_lower = re.sub(r'(?<=[\d\s\-_])' + re.escape(fr) + r'(?=[\d\s\-_]|$)', en, s_lower)
            break

    try:
        import dateutil.parser
        dt = dateutil.parser.parse(s_lower, dayfirst=True)
        return dt.date()
    except Exception:
        # Fallback regex for DD-MM-YY or DD-MM-YYYY
        m = re.search(r"(\d{1,2})[-/\s](\d{1,2})[-/\s](\d{2,4})", s)
        if m:
            d_val, m_num, y = int(m.group(1)), int(m.group(2)), int(m.group(3))
            if y < 100:
                # Only in this path can we confirm the year was 2-digit in the source.
                # Always map to 20xx for certificate documents (99  2099, 24  2024).
                y += 2000
            try:
                return date(y, m_num, d_val)
            except Exception:
                pass

    logger.warning(f"Unable to parse date string '{date_str}'.")
    return None



def extract_certificate_data(
    raw_markdown: str, file_name: str, db_session: Optional[Session] = None
) -> CertificateExtractionSchema:
    """
    Extract structured data from raw Markdown text using an LLM and optionally enrich via DB.
    
    Args:
        raw_markdown: The markdown text output from the active OCR engine.
        file_name: The original filename, preserved for traceability.
        db_session: Optional active SQLAlchemy Session for lookup table enrichment.
        
    Returns:
        A validated and enriched CertificateExtractionSchema object.
    """
    # 1. Construct the LLM payload (engine formats system/user into its own template).
    from server.config import MAX_EXTRACTION_PROMPT_CHARS
    full_text = raw_markdown
    if len(raw_markdown) > MAX_EXTRACTION_PROMPT_CHARS:
        logger.warning(
            f"  Truncating extraction document from {len(raw_markdown)} to "
            f"{MAX_EXTRACTION_PROMPT_CHARS} chars to fit the LLM context window."
        )
        raw_markdown = raw_markdown[:MAX_EXTRACTION_PROMPT_CHARS]

    user_prompt = f"--- BEGIN DOCUMENT: {file_name} ---\n"
    user_prompt += f"{raw_markdown}\n"
    user_prompt += "--- END DOCUMENT ---\n\n"
    user_prompt += "Return ONLY the raw JSON output."

    # 2. Call the LLM engine to get the pure JSON string response (Full Reasoning Mode)
    from core.llm import generate_json
    from core.utils.vram import flush_gpu_cache, ensure_headroom
    from server.config import MIN_FREE_VRAM_MB
    flush_gpu_cache()
    ensure_headroom(MIN_FREE_VRAM_MB, "LLM extraction")
    raw_json_response = generate_json(
        system_prompt=CERTIFICATE_EXTRACTION_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        disable_thinking=False,
    )

    # 3. Parse and Validate with fallback
    try:
        parsed_data = CertificateExtractionSchema.model_validate_json(raw_json_response)
    except (json.JSONDecodeError, pydantic.ValidationError) as e:
        logger.warning(f"  JSON/Pydantic validation failed for {file_name}: {e}")
        logger.info("    Falling back to default 'Not Found' values to prevent crash.")
        
        parsed_data = CertificateExtractionSchema(
            component="Not Found",
            supplier="Not Found",
            country=None,
            certif_number="Not Found",
            authority="Not Found",
            issue_date=None,
            exp_date=None,
        )

    # 4. Enrich metadata with database lookups if db_session is provided
    if db_session is not None:
        parsed_data = enrich_certificate_metadata(parsed_data, db_session)

    return parsed_data


def find_existing_certificate(
    db: Session,
    file_name: Optional[str] = None,
    certif_number: Optional[str] = None,
    country: Optional[str] = None,
):
    """
    Locates an existing certificate record that a new ingestion should supersede.

    Anti-duplicate identity, evaluated in priority order:
      1. `certif_number` + `country` (case-insensitive) -- the strongest identity,
         used whenever both are known. Handles the same certificate re-ingested
         under a different filename, and multi-record CSV/Excel imports where many
         distinct certificates share the source `file_name`.
      2. `file_name` (case-insensitive) -- fallback identity used only when the
         certificate number is unavailable (e.g. a batch re-upload whose
         extraction produced no certif number).

    Returns the matching `CertificateMetadata` row or None.
    """
    from sqlalchemy import func
    from schemas.extraction import CertificateMetadata

    if certif_number and country:
        cn = str(certif_number).strip().lower()
        co = str(country).strip().lower()
        if cn and co:
            rec = (
                db.query(CertificateMetadata)
                .filter(
                    func.lower(CertificateMetadata.certif_number) == cn,
                    func.lower(CertificateMetadata.country) == co,
                )
                .first()
            )
            if rec is not None:
                return rec

    if file_name and str(file_name).strip():
        norm = str(file_name).strip().lower()
        rec = (
            db.query(CertificateMetadata)
            .filter(func.lower(CertificateMetadata.file_name) == norm)
            .first()
        )
        if rec is not None:
            return rec

    return None


def save_certificate_to_db(
    cert_data: CertificateExtractionSchema,
    raw_markdown: str,
    file_name: str,
    db: Optional[Session] = None,
    dedup_file_name: bool = True,
) -> CertificateMetadata:
    """
    Persists structured certificate metadata and vector-embedded chunks into PostgreSQL.

    Anti-duplicate behavior: if an existing record matches the incoming data
    (case-insensitive `file_name`, or `certif_number` + `country`), the existing
    record is updated in place and its vector chunks are replaced instead of
    inserting a duplicate row.

    Operation Steps:
      1. Performs lookup table enrichment on Pydantic certificate schema.
      2. Normalizes Pydantic fields to CertificateMetadata ORM values.
      3. Detects an existing duplicate and updates it, or creates a new record.
      4. Chunks layout-aware markdown text via chunk_for_qa().
      5. Computes 1024-dimensional BAAI/bge-m3 embeddings for every chunk.
      6. Binds chunks to the metadata record via certificate_id FK and commits.

    Args:
        cert_data: Validated extraction schema.
        raw_markdown: OCR markdown text.
        file_name: Source document file name.
        db: Optional session (auto-managed when None).
        dedup_file_name: When False, the case-insensitive file_name identity is
            skipped (used for manual entries that share a synthetic file name).

    Returns:
        CertificateMetadata: Persisted ORM metadata object.
    """
    close_session_on_exit = False
    if db is None:
        from storage.database import SessionLocal
        db = SessionLocal()
        close_session_on_exit = True

    try:
        # Perform lookup table enrichment before converting to ORM record
        cert_data = enrich_certificate_metadata(cert_data, db)

        # Normalize fields from Pydantic schema
        component = cert_data.component if cert_data.component != "Not Found" else None
        supplier = cert_data.supplier if cert_data.supplier != "Not Found" else None
        country = cert_data.country if cert_data.country != "Not Found" else None
        certif_number = cert_data.certif_number if getattr(cert_data, "certif_number", "Not Found") != "Not Found" else None
        authority = cert_data.authority if cert_data.authority != "Not Found" else None
        issue_dt = _parse_iso_date(cert_data.issue_date)
        exp_dt = _parse_iso_date(cert_data.exp_date)
        cert_link = getattr(cert_data, "cert_link", None) or None

        # ── Anti-duplicate: supersede an existing record if one matches ──
        existing = find_existing_certificate(
            db,
            file_name=file_name if dedup_file_name else None,
            certif_number=certif_number,
            country=country,
        )
        updated = False
        if existing is not None:
            cert_id = existing.certificate_id
            existing.component = component
            existing.supplier = supplier
            existing.country = country
            existing.certif_number = certif_number
            existing.authority = authority
            existing.issue_date = issue_dt
            existing.exp_date = exp_dt
            existing.cert_link = cert_link
            existing.file_name = file_name
            existing.created_at = datetime.utcnow()
            # Replace the old vector chunks so retrieval reflects the new content.
            db.query(CertificateChunk).filter(CertificateChunk.certificate_id == cert_id).delete()
            metadata_record = existing
            updated = True
        else:
            cert_id = f"cert_{uuid.uuid4().hex[:12]}"
            metadata_record = CertificateMetadata(
                certificate_id=cert_id,
                component=component,
                supplier=supplier,
                country=country,
                certif_number=certif_number,
                authority=authority,
                issue_date=issue_dt,
                exp_date=exp_dt,
                cert_link=cert_link,
                file_name=file_name
            )
            db.add(metadata_record)

        # 2. Chunk markdown text
        raw_chunks = chunk_for_qa(raw_markdown, file_name, document_id=cert_id)
        chunk_texts = [c.get("content", "") for c in raw_chunks]

        # 3. Compute 1024-d dense vector embeddings via BAAI/bge-m3
        logger.info(f"Computing 1024-d embeddings for {len(chunk_texts)} chunks...")
        embeddings = get_embeddings_batch(chunk_texts)

        # 4. Construct CertificateChunk ORM instances
        chunk_records = []
        for idx, chunk_info in enumerate(raw_chunks):
            pg_num = chunk_info.get("page_number")
            if isinstance(pg_num, str) and pg_num.isdigit():
                pg_num = int(pg_num)
            elif not isinstance(pg_num, int):
                pg_num = 1

            chunk_orm = CertificateChunk(
                certificate_id=cert_id,
                page_number=pg_num,
                raw_text=chunk_info.get("content", ""),
                embedding=embeddings[idx] if idx < len(embeddings) else [0.0] * 1024
            )
            chunk_records.append(chunk_orm)

        db.add_all(chunk_records)
        db.commit()
        db.refresh(metadata_record)
        metadata_record._is_updated = updated
        action = "Updated" if updated else "Successfully persisted"
        logger.info(f" {action} Certificate '{cert_id}' with {len(chunk_records)} chunks to PostgreSQL.")
        
        # Trigger automated backup in background thread
        from storage.backup import trigger_async_backup
        trigger_async_backup()
        
        return metadata_record
    except Exception as e:
        db.rollback()
        logger.error(f" Database error persisting Certificate '{cert_id}': {e}")
        raise
    finally:
        if close_session_on_exit:
            db.close()
