[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#243881"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"
